# Generated by Django 2.2.2 on 2019-12-14 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_user_last_seen_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='message_id',
            new_name='message_user_a_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='sent_at',
            new_name='sent_user_a_at',
        ),
        migrations.AddField(
            model_name='meeting',
            name='message_user_b_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sent_user_b_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_a_meeting_failure_reason',
            field=models.CharField(choices=[('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_b_meeting_failure_reason',
            field=models.CharField(choices=[('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], max_length=100),
        ),
    ]
